<Project Sdk="Microsoft.NET.Sdk">
  <!-- APPLICATION / BUSINESS LAYER. References ONLY Domain.
       Never references Infrastructure or any Hal.Vendor.* project.
       Owner: Back-End Developer. -->
  <PropertyGroup>
    <RootNamespace>SelfCheckoutKiosk.Core</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Workloads.10.0.100" Version="10.110.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SelfCheckoutKiosk.Domain\SelfCheckoutKiosk.Domain.csproj" />
  </ItemGroup>
</Project>
