<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SelfCheckoutKiosk.Core</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\SelfCheckoutKiosk.Domain\SelfCheckoutKiosk.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SelfCheckoutKiosk.Core.Tests" />
    <InternalsVisibleTo Include="SelfCheckoutKiosk.Integration.Tests" />
  </ItemGroup>

</Project>