<Project Sdk="Microsoft.NET.Sdk">
  <!-- APPLICATION / BUSINESS LAYER. References ONLY Domain.
       Never references Infrastructure or any Hal.Vendor.* project.
       Owner: Back-End Developer. -->
  <PropertyGroup>
    <RootNamespace>SelfCheckoutKiosk.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SelfCheckoutKiosk.Domain\SelfCheckoutKiosk.Domain.csproj" />
  </ItemGroup>
</Project>
