// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    public partial class KioskDbContextModel
    {
        private KioskDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("9098319a-7729-4313-9c4c-7cee90a8733d"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var licenseConfiguration = LicenseConfigurationEntityType.Create(this);
            var lineItem = LineItemEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var transaction = TransactionEntityType.Create(this);

            LineItemEntityType.CreateForeignKey1(lineItem, transaction);

            LicenseConfigurationEntityType.CreateAnnotations(licenseConfiguration);
            LineItemEntityType.CreateAnnotations(lineItem);
            ProductEntityType.CreateAnnotations(product);
            TransactionEntityType.CreateAnnotations(transaction);

            AddAnnotation("ProductVersion", "9.0.0");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var licenseConfiguration = FindEntityType("SelfCheckoutKiosk.Domain.Entities.LicenseConfiguration")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            licenseConfiguration.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase = new TableBase("SelfCheckoutKiosk.Domain.Entities.LicenseConfiguration", null, relationalModel);
            var expiresAtUtcColumnBase = new ColumnBase<ColumnMappingBase>("ExpiresAtUtc", "TEXT", selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase);
            selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase.Columns.Add("ExpiresAtUtc", expiresAtUtcColumnBase);
            var hardwareIdColumnBase = new ColumnBase<ColumnMappingBase>("HardwareId", "TEXT", selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase);
            selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase.Columns.Add("HardwareId", hardwareIdColumnBase);
            var maxKiosksColumnBase = new ColumnBase<ColumnMappingBase>("MaxKiosks", "INTEGER", selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase);
            selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase.Columns.Add("MaxKiosks", maxKiosksColumnBase);
            var tierColumnBase = new ColumnBase<ColumnMappingBase>("Tier", "TEXT", selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase);
            selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase.Columns.Add("Tier", tierColumnBase);
            relationalModel.DefaultTables.Add("SelfCheckoutKiosk.Domain.Entities.LicenseConfiguration", selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase);
            var selfCheckoutKioskDomainEntitiesLicenseConfigurationMappingBase = new TableMappingBase<ColumnMappingBase>(licenseConfiguration, selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase, null);
            selfCheckoutKioskDomainEntitiesLicenseConfigurationTableBase.AddTypeMapping(selfCheckoutKioskDomainEntitiesLicenseConfigurationMappingBase, false);
            defaultTableMappings.Add(selfCheckoutKioskDomainEntitiesLicenseConfigurationMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)hardwareIdColumnBase, licenseConfiguration.FindProperty("HardwareId")!, selfCheckoutKioskDomainEntitiesLicenseConfigurationMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)expiresAtUtcColumnBase, licenseConfiguration.FindProperty("ExpiresAtUtc")!, selfCheckoutKioskDomainEntitiesLicenseConfigurationMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)maxKiosksColumnBase, licenseConfiguration.FindProperty("MaxKiosks")!, selfCheckoutKioskDomainEntitiesLicenseConfigurationMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tierColumnBase, licenseConfiguration.FindProperty("Tier")!, selfCheckoutKioskDomainEntitiesLicenseConfigurationMappingBase);

            var tableMappings = new List<TableMapping>();
            licenseConfiguration.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var licenseConfigurationsTable = new Table("LicenseConfigurations", null, relationalModel);
            var hardwareIdColumn = new Column("HardwareId", "TEXT", licenseConfigurationsTable);
            licenseConfigurationsTable.Columns.Add("HardwareId", hardwareIdColumn);
            hardwareIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(hardwareIdColumn);
            var expiresAtUtcColumn = new Column("ExpiresAtUtc", "TEXT", licenseConfigurationsTable);
            licenseConfigurationsTable.Columns.Add("ExpiresAtUtc", expiresAtUtcColumn);
            expiresAtUtcColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(expiresAtUtcColumn);
            var maxKiosksColumn = new Column("MaxKiosks", "INTEGER", licenseConfigurationsTable);
            licenseConfigurationsTable.Columns.Add("MaxKiosks", maxKiosksColumn);
            maxKiosksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(maxKiosksColumn);
            var tierColumn = new Column("Tier", "TEXT", licenseConfigurationsTable);
            licenseConfigurationsTable.Columns.Add("Tier", tierColumn);
            tierColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(tierColumn);
            relationalModel.Tables.Add(("LicenseConfigurations", null), licenseConfigurationsTable);
            var licenseConfigurationsTableMapping = new TableMapping(licenseConfiguration, licenseConfigurationsTable, null);
            licenseConfigurationsTable.AddTypeMapping(licenseConfigurationsTableMapping, false);
            tableMappings.Add(licenseConfigurationsTableMapping);
            RelationalModel.CreateColumnMapping(hardwareIdColumn, licenseConfiguration.FindProperty("HardwareId")!, licenseConfigurationsTableMapping);
            RelationalModel.CreateColumnMapping(expiresAtUtcColumn, licenseConfiguration.FindProperty("ExpiresAtUtc")!, licenseConfigurationsTableMapping);
            RelationalModel.CreateColumnMapping(maxKiosksColumn, licenseConfiguration.FindProperty("MaxKiosks")!, licenseConfigurationsTableMapping);
            RelationalModel.CreateColumnMapping(tierColumn, licenseConfiguration.FindProperty("Tier")!, licenseConfigurationsTableMapping);
            var pK_LicenseConfigurations = new UniqueConstraint("PK_LicenseConfigurations", licenseConfigurationsTable, new[] { hardwareIdColumn });
            licenseConfigurationsTable.PrimaryKey = pK_LicenseConfigurations;
            pK_LicenseConfigurations.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_LicenseConfigurations));
            var pK_LicenseConfigurationsKey = RelationalModel.GetKey(this,
                "SelfCheckoutKiosk.Domain.Entities.LicenseConfiguration",
                new[] { "HardwareId" });
            pK_LicenseConfigurations.MappedKeys.Add(pK_LicenseConfigurationsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_LicenseConfigurationsKey).Add(pK_LicenseConfigurations);
            licenseConfigurationsTable.UniqueConstraints.Add("PK_LicenseConfigurations", pK_LicenseConfigurations);

            var lineItem = FindEntityType("SelfCheckoutKiosk.Domain.Entities.LineItem")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            lineItem.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var selfCheckoutKioskDomainEntitiesLineItemTableBase = new TableBase("SelfCheckoutKiosk.Domain.Entities.LineItem", null, relationalModel);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "TEXT", selfCheckoutKioskDomainEntitiesLineItemTableBase);
            selfCheckoutKioskDomainEntitiesLineItemTableBase.Columns.Add("Description", descriptionColumnBase);
            var ean13ColumnBase = new ColumnBase<ColumnMappingBase>("Ean13", "TEXT", selfCheckoutKioskDomainEntitiesLineItemTableBase);
            selfCheckoutKioskDomainEntitiesLineItemTableBase.Columns.Add("Ean13", ean13ColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", selfCheckoutKioskDomainEntitiesLineItemTableBase);
            selfCheckoutKioskDomainEntitiesLineItemTableBase.Columns.Add("Id", idColumnBase);
            var quantityColumnBase = new ColumnBase<ColumnMappingBase>("Quantity", "INTEGER", selfCheckoutKioskDomainEntitiesLineItemTableBase);
            selfCheckoutKioskDomainEntitiesLineItemTableBase.Columns.Add("Quantity", quantityColumnBase);
            var transactionGuidColumnBase = new ColumnBase<ColumnMappingBase>("TransactionGuid", "TEXT", selfCheckoutKioskDomainEntitiesLineItemTableBase);
            selfCheckoutKioskDomainEntitiesLineItemTableBase.Columns.Add("TransactionGuid", transactionGuidColumnBase);
            var unitPriceUsdColumnBase = new ColumnBase<ColumnMappingBase>("UnitPriceUsd", "TEXT", selfCheckoutKioskDomainEntitiesLineItemTableBase);
            selfCheckoutKioskDomainEntitiesLineItemTableBase.Columns.Add("UnitPriceUsd", unitPriceUsdColumnBase);
            relationalModel.DefaultTables.Add("SelfCheckoutKiosk.Domain.Entities.LineItem", selfCheckoutKioskDomainEntitiesLineItemTableBase);
            var selfCheckoutKioskDomainEntitiesLineItemMappingBase = new TableMappingBase<ColumnMappingBase>(lineItem, selfCheckoutKioskDomainEntitiesLineItemTableBase, null);
            selfCheckoutKioskDomainEntitiesLineItemTableBase.AddTypeMapping(selfCheckoutKioskDomainEntitiesLineItemMappingBase, false);
            defaultTableMappings0.Add(selfCheckoutKioskDomainEntitiesLineItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, lineItem.FindProperty("Id")!, selfCheckoutKioskDomainEntitiesLineItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, lineItem.FindProperty("Description")!, selfCheckoutKioskDomainEntitiesLineItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ean13ColumnBase, lineItem.FindProperty("Ean13")!, selfCheckoutKioskDomainEntitiesLineItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)quantityColumnBase, lineItem.FindProperty("Quantity")!, selfCheckoutKioskDomainEntitiesLineItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)transactionGuidColumnBase, lineItem.FindProperty("TransactionGuid")!, selfCheckoutKioskDomainEntitiesLineItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)unitPriceUsdColumnBase, lineItem.FindProperty("UnitPriceUsd")!, selfCheckoutKioskDomainEntitiesLineItemMappingBase);

            var tableMappings0 = new List<TableMapping>();
            lineItem.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var lineItemTable = new Table("LineItem", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", lineItemTable);
            lineItemTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            var descriptionColumn = new Column("Description", "TEXT", lineItemTable);
            lineItemTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var ean13Column = new Column("Ean13", "TEXT", lineItemTable);
            lineItemTable.Columns.Add("Ean13", ean13Column);
            ean13Column.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(ean13Column);
            var quantityColumn = new Column("Quantity", "INTEGER", lineItemTable);
            lineItemTable.Columns.Add("Quantity", quantityColumn);
            quantityColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(quantityColumn);
            var transactionGuidColumn = new Column("TransactionGuid", "TEXT", lineItemTable);
            lineItemTable.Columns.Add("TransactionGuid", transactionGuidColumn);
            transactionGuidColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(transactionGuidColumn);
            var unitPriceUsdColumn = new Column("UnitPriceUsd", "TEXT", lineItemTable);
            lineItemTable.Columns.Add("UnitPriceUsd", unitPriceUsdColumn);
            unitPriceUsdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<decimal>(unitPriceUsdColumn);
            relationalModel.Tables.Add(("LineItem", null), lineItemTable);
            var lineItemTableMapping = new TableMapping(lineItem, lineItemTable, null);
            lineItemTable.AddTypeMapping(lineItemTableMapping, false);
            tableMappings0.Add(lineItemTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, lineItem.FindProperty("Id")!, lineItemTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, lineItem.FindProperty("Description")!, lineItemTableMapping);
            RelationalModel.CreateColumnMapping(ean13Column, lineItem.FindProperty("Ean13")!, lineItemTableMapping);
            RelationalModel.CreateColumnMapping(quantityColumn, lineItem.FindProperty("Quantity")!, lineItemTableMapping);
            RelationalModel.CreateColumnMapping(transactionGuidColumn, lineItem.FindProperty("TransactionGuid")!, lineItemTableMapping);
            RelationalModel.CreateColumnMapping(unitPriceUsdColumn, lineItem.FindProperty("UnitPriceUsd")!, lineItemTableMapping);
            var pK_LineItem = new UniqueConstraint("PK_LineItem", lineItemTable, new[] { idColumn });
            lineItemTable.PrimaryKey = pK_LineItem;
            pK_LineItem.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_LineItem));
            var pK_LineItemKey = RelationalModel.GetKey(this,
                "SelfCheckoutKiosk.Domain.Entities.LineItem",
                new[] { "Id" });
            pK_LineItem.MappedKeys.Add(pK_LineItemKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_LineItemKey).Add(pK_LineItem);
            lineItemTable.UniqueConstraints.Add("PK_LineItem", pK_LineItem);
            var iX_LineItem_TransactionGuid = new TableIndex(
            "IX_LineItem_TransactionGuid", lineItemTable, new[] { transactionGuidColumn }, false);
            iX_LineItem_TransactionGuid.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_LineItem_TransactionGuid));
            var iX_LineItem_TransactionGuidIx = RelationalModel.GetIndex(this,
                "SelfCheckoutKiosk.Domain.Entities.LineItem",
                new[] { "TransactionGuid" });
            iX_LineItem_TransactionGuid.MappedIndexes.Add(iX_LineItem_TransactionGuidIx);
            RelationalModel.GetOrCreateTableIndexes(iX_LineItem_TransactionGuidIx).Add(iX_LineItem_TransactionGuid);
            lineItemTable.Indexes.Add("IX_LineItem_TransactionGuid", iX_LineItem_TransactionGuid);

            var product = FindEntityType("SelfCheckoutKiosk.Domain.Entities.Product")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            product.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var selfCheckoutKioskDomainEntitiesProductTableBase = new TableBase("SelfCheckoutKiosk.Domain.Entities.Product", null, relationalModel);
            var descriptionColumnBase0 = new ColumnBase<ColumnMappingBase>("Description", "TEXT", selfCheckoutKioskDomainEntitiesProductTableBase);
            selfCheckoutKioskDomainEntitiesProductTableBase.Columns.Add("Description", descriptionColumnBase0);
            var ean13ColumnBase0 = new ColumnBase<ColumnMappingBase>("Ean13", "TEXT", selfCheckoutKioskDomainEntitiesProductTableBase);
            selfCheckoutKioskDomainEntitiesProductTableBase.Columns.Add("Ean13", ean13ColumnBase0);
            var khrPriceColumnBase = new ColumnBase<ColumnMappingBase>("KhrPrice", "TEXT", selfCheckoutKioskDomainEntitiesProductTableBase);
            selfCheckoutKioskDomainEntitiesProductTableBase.Columns.Add("KhrPrice", khrPriceColumnBase);
            var usdPriceColumnBase = new ColumnBase<ColumnMappingBase>("UsdPrice", "TEXT", selfCheckoutKioskDomainEntitiesProductTableBase);
            selfCheckoutKioskDomainEntitiesProductTableBase.Columns.Add("UsdPrice", usdPriceColumnBase);
            relationalModel.DefaultTables.Add("SelfCheckoutKiosk.Domain.Entities.Product", selfCheckoutKioskDomainEntitiesProductTableBase);
            var selfCheckoutKioskDomainEntitiesProductMappingBase = new TableMappingBase<ColumnMappingBase>(product, selfCheckoutKioskDomainEntitiesProductTableBase, null);
            selfCheckoutKioskDomainEntitiesProductTableBase.AddTypeMapping(selfCheckoutKioskDomainEntitiesProductMappingBase, false);
            defaultTableMappings1.Add(selfCheckoutKioskDomainEntitiesProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ean13ColumnBase0, product.FindProperty("Ean13")!, selfCheckoutKioskDomainEntitiesProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase0, product.FindProperty("Description")!, selfCheckoutKioskDomainEntitiesProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)khrPriceColumnBase, product.FindProperty("KhrPrice")!, selfCheckoutKioskDomainEntitiesProductMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)usdPriceColumnBase, product.FindProperty("UsdPrice")!, selfCheckoutKioskDomainEntitiesProductMappingBase);

            var tableMappings1 = new List<TableMapping>();
            product.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var productsTable = new Table("Products", null, relationalModel);
            var ean13Column0 = new Column("Ean13", "TEXT", productsTable);
            productsTable.Columns.Add("Ean13", ean13Column0);
            ean13Column0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(ean13Column0);
            var descriptionColumn0 = new Column("Description", "TEXT", productsTable);
            productsTable.Columns.Add("Description", descriptionColumn0);
            descriptionColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn0);
            var khrPriceColumn = new Column("KhrPrice", "TEXT", productsTable);
            productsTable.Columns.Add("KhrPrice", khrPriceColumn);
            khrPriceColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<decimal>(khrPriceColumn);
            var usdPriceColumn = new Column("UsdPrice", "TEXT", productsTable);
            productsTable.Columns.Add("UsdPrice", usdPriceColumn);
            usdPriceColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<decimal>(usdPriceColumn);
            relationalModel.Tables.Add(("Products", null), productsTable);
            var productsTableMapping = new TableMapping(product, productsTable, null);
            productsTable.AddTypeMapping(productsTableMapping, false);
            tableMappings1.Add(productsTableMapping);
            RelationalModel.CreateColumnMapping(ean13Column0, product.FindProperty("Ean13")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn0, product.FindProperty("Description")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(khrPriceColumn, product.FindProperty("KhrPrice")!, productsTableMapping);
            RelationalModel.CreateColumnMapping(usdPriceColumn, product.FindProperty("UsdPrice")!, productsTableMapping);
            var pK_Products = new UniqueConstraint("PK_Products", productsTable, new[] { ean13Column0 });
            productsTable.PrimaryKey = pK_Products;
            pK_Products.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_Products));
            var pK_ProductsKey = RelationalModel.GetKey(this,
                "SelfCheckoutKiosk.Domain.Entities.Product",
                new[] { "Ean13" });
            pK_Products.MappedKeys.Add(pK_ProductsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ProductsKey).Add(pK_Products);
            productsTable.UniqueConstraints.Add("PK_Products", pK_Products);

            var transaction = FindEntityType("SelfCheckoutKiosk.Domain.Entities.Transaction")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            transaction.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var selfCheckoutKioskDomainEntitiesTransactionTableBase = new TableBase("SelfCheckoutKiosk.Domain.Entities.Transaction", null, relationalModel);
            var createdAtUtcColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAtUtc", "TEXT", selfCheckoutKioskDomainEntitiesTransactionTableBase);
            selfCheckoutKioskDomainEntitiesTransactionTableBase.Columns.Add("CreatedAtUtc", createdAtUtcColumnBase);
            var paymentMethodColumnBase = new ColumnBase<ColumnMappingBase>("PaymentMethod", "INTEGER", selfCheckoutKioskDomainEntitiesTransactionTableBase)
            {
                IsNullable = true
            };
            selfCheckoutKioskDomainEntitiesTransactionTableBase.Columns.Add("PaymentMethod", paymentMethodColumnBase);
            var syncStatusColumnBase = new ColumnBase<ColumnMappingBase>("SyncStatus", "TEXT", selfCheckoutKioskDomainEntitiesTransactionTableBase);
            selfCheckoutKioskDomainEntitiesTransactionTableBase.Columns.Add("SyncStatus", syncStatusColumnBase);
            var tenderedUsdColumnBase = new ColumnBase<ColumnMappingBase>("TenderedUsd", "TEXT", selfCheckoutKioskDomainEntitiesTransactionTableBase);
            selfCheckoutKioskDomainEntitiesTransactionTableBase.Columns.Add("TenderedUsd", tenderedUsdColumnBase);
            var totalUsdColumnBase = new ColumnBase<ColumnMappingBase>("TotalUsd", "TEXT", selfCheckoutKioskDomainEntitiesTransactionTableBase);
            selfCheckoutKioskDomainEntitiesTransactionTableBase.Columns.Add("TotalUsd", totalUsdColumnBase);
            var transactionGuidColumnBase0 = new ColumnBase<ColumnMappingBase>("TransactionGuid", "TEXT", selfCheckoutKioskDomainEntitiesTransactionTableBase);
            selfCheckoutKioskDomainEntitiesTransactionTableBase.Columns.Add("TransactionGuid", transactionGuidColumnBase0);
            relationalModel.DefaultTables.Add("SelfCheckoutKiosk.Domain.Entities.Transaction", selfCheckoutKioskDomainEntitiesTransactionTableBase);
            var selfCheckoutKioskDomainEntitiesTransactionMappingBase = new TableMappingBase<ColumnMappingBase>(transaction, selfCheckoutKioskDomainEntitiesTransactionTableBase, null);
            selfCheckoutKioskDomainEntitiesTransactionTableBase.AddTypeMapping(selfCheckoutKioskDomainEntitiesTransactionMappingBase, false);
            defaultTableMappings2.Add(selfCheckoutKioskDomainEntitiesTransactionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)transactionGuidColumnBase0, transaction.FindProperty("TransactionGuid")!, selfCheckoutKioskDomainEntitiesTransactionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtUtcColumnBase, transaction.FindProperty("CreatedAtUtc")!, selfCheckoutKioskDomainEntitiesTransactionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)paymentMethodColumnBase, transaction.FindProperty("PaymentMethod")!, selfCheckoutKioskDomainEntitiesTransactionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)syncStatusColumnBase, transaction.FindProperty("SyncStatus")!, selfCheckoutKioskDomainEntitiesTransactionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tenderedUsdColumnBase, transaction.FindProperty("TenderedUsd")!, selfCheckoutKioskDomainEntitiesTransactionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)totalUsdColumnBase, transaction.FindProperty("TotalUsd")!, selfCheckoutKioskDomainEntitiesTransactionMappingBase);

            var tableMappings2 = new List<TableMapping>();
            transaction.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var transactionsTable = new Table("Transactions", null, relationalModel);
            var transactionGuidColumn0 = new Column("TransactionGuid", "TEXT", transactionsTable);
            transactionsTable.Columns.Add("TransactionGuid", transactionGuidColumn0);
            transactionGuidColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(transactionGuidColumn0);
            var createdAtUtcColumn = new Column("CreatedAtUtc", "TEXT", transactionsTable);
            transactionsTable.Columns.Add("CreatedAtUtc", createdAtUtcColumn);
            createdAtUtcColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(createdAtUtcColumn);
            var paymentMethodColumn = new Column("PaymentMethod", "INTEGER", transactionsTable)
            {
                IsNullable = true
            };
            transactionsTable.Columns.Add("PaymentMethod", paymentMethodColumn);
            paymentMethodColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(paymentMethodColumn);
            var syncStatusColumn = new Column("SyncStatus", "TEXT", transactionsTable);
            transactionsTable.Columns.Add("SyncStatus", syncStatusColumn);
            syncStatusColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(syncStatusColumn);
            var tenderedUsdColumn = new Column("TenderedUsd", "TEXT", transactionsTable);
            transactionsTable.Columns.Add("TenderedUsd", tenderedUsdColumn);
            tenderedUsdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<decimal>(tenderedUsdColumn);
            var totalUsdColumn = new Column("TotalUsd", "TEXT", transactionsTable);
            transactionsTable.Columns.Add("TotalUsd", totalUsdColumn);
            totalUsdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<decimal>(totalUsdColumn);
            relationalModel.Tables.Add(("Transactions", null), transactionsTable);
            var transactionsTableMapping = new TableMapping(transaction, transactionsTable, null);
            transactionsTable.AddTypeMapping(transactionsTableMapping, false);
            tableMappings2.Add(transactionsTableMapping);
            RelationalModel.CreateColumnMapping(transactionGuidColumn0, transaction.FindProperty("TransactionGuid")!, transactionsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtUtcColumn, transaction.FindProperty("CreatedAtUtc")!, transactionsTableMapping);
            RelationalModel.CreateColumnMapping(paymentMethodColumn, transaction.FindProperty("PaymentMethod")!, transactionsTableMapping);
            RelationalModel.CreateColumnMapping(syncStatusColumn, transaction.FindProperty("SyncStatus")!, transactionsTableMapping);
            RelationalModel.CreateColumnMapping(tenderedUsdColumn, transaction.FindProperty("TenderedUsd")!, transactionsTableMapping);
            RelationalModel.CreateColumnMapping(totalUsdColumn, transaction.FindProperty("TotalUsd")!, transactionsTableMapping);
            var pK_Transactions = new UniqueConstraint("PK_Transactions", transactionsTable, new[] { transactionGuidColumn0 });
            transactionsTable.PrimaryKey = pK_Transactions;
            pK_Transactions.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Transactions));
            var pK_TransactionsKey = RelationalModel.GetKey(this,
                "SelfCheckoutKiosk.Domain.Entities.Transaction",
                new[] { "TransactionGuid" });
            pK_Transactions.MappedKeys.Add(pK_TransactionsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_TransactionsKey).Add(pK_Transactions);
            transactionsTable.UniqueConstraints.Add("PK_Transactions", pK_Transactions);
            var fK_LineItem_Transactions_TransactionGuid = new ForeignKeyConstraint(
                "FK_LineItem_Transactions_TransactionGuid", lineItemTable, transactionsTable,
                new[] { transactionGuidColumn },
                transactionsTable.FindUniqueConstraint("PK_Transactions")!, ReferentialAction.Cascade);
            fK_LineItem_Transactions_TransactionGuid.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_LineItem_Transactions_TransactionGuid));
            var fK_LineItem_Transactions_TransactionGuidFk = RelationalModel.GetForeignKey(this,
                "SelfCheckoutKiosk.Domain.Entities.LineItem",
                new[] { "TransactionGuid" },
                "SelfCheckoutKiosk.Domain.Entities.Transaction",
                new[] { "TransactionGuid" });
            fK_LineItem_Transactions_TransactionGuid.MappedForeignKeys.Add(fK_LineItem_Transactions_TransactionGuidFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_LineItem_Transactions_TransactionGuidFk).Add(fK_LineItem_Transactions_TransactionGuid);
            lineItemTable.ForeignKeyConstraints.Add(fK_LineItem_Transactions_TransactionGuid);
            transactionsTable.ReferencingForeignKeyConstraints.Add(fK_LineItem_Transactions_TransactionGuid);
            return relationalModel.MakeReadOnly();
        }
    }
}
