// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using SelfCheckoutKiosk.Infrastructure.Data;
using SelfCheckoutKiosk.Infrastructure.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(KioskDbContext), typeof(KioskDbContextModel))]
