// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using SelfCheckoutKiosk.Domain.Entities;
using SelfCheckoutKiosk.Domain.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    public static class LicenseConfigurationUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<HardwareId>k__BackingField")]
        public static extern ref string HardwareId(LicenseConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresAtUtc>k__BackingField")]
        public static extern ref DateTimeOffset ExpiresAtUtc(LicenseConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxKiosks>k__BackingField")]
        public static extern ref int MaxKiosks(LicenseConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Tier>k__BackingField")]
        public static extern ref LicenseTier Tier(LicenseConfiguration @this);
    }
}
