// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using SelfCheckoutKiosk.Domain.Entities;
using SelfCheckoutKiosk.Domain.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class LicenseConfigurationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SelfCheckoutKiosk.Domain.Entities.LicenseConfiguration",
                typeof(LicenseConfiguration),
                baseEntityType,
                propertyCount: 4,
                keyCount: 1);

            var hardwareId = runtimeEntityType.AddProperty(
                "HardwareId",
                typeof(string),
                propertyInfo: typeof(LicenseConfiguration).GetProperty("HardwareId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LicenseConfiguration).GetField("<HardwareId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            hardwareId.SetGetter(
                string (LicenseConfiguration entity) => LicenseConfigurationUnsafeAccessors.HardwareId(entity),
                bool (LicenseConfiguration entity) => LicenseConfigurationUnsafeAccessors.HardwareId(entity) == null,
                string (LicenseConfiguration instance) => LicenseConfigurationUnsafeAccessors.HardwareId(instance),
                bool (LicenseConfiguration instance) => LicenseConfigurationUnsafeAccessors.HardwareId(instance) == null);
            hardwareId.SetSetter(
                (LicenseConfiguration entity, string value) => LicenseConfigurationUnsafeAccessors.HardwareId(entity) = value);
            hardwareId.SetMaterializationSetter(
                (LicenseConfiguration entity, string value) => LicenseConfigurationUnsafeAccessors.HardwareId(entity) = value);
            hardwareId.SetAccessors(
                string (InternalEntityEntry entry) => LicenseConfigurationUnsafeAccessors.HardwareId(((LicenseConfiguration)(entry.Entity))),
                string (InternalEntityEntry entry) => LicenseConfigurationUnsafeAccessors.HardwareId(((LicenseConfiguration)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(hardwareId, 0),
                string (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<string>(hardwareId, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            hardwareId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            hardwareId.TypeMapping = SqliteStringTypeMapping.Default;
            hardwareId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(hardwareId));

            var expiresAtUtc = runtimeEntityType.AddProperty(
                "ExpiresAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(LicenseConfiguration).GetProperty("ExpiresAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LicenseConfiguration).GetField("<ExpiresAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            expiresAtUtc.SetGetter(
                DateTimeOffset (LicenseConfiguration entity) => LicenseConfigurationUnsafeAccessors.ExpiresAtUtc(entity),
                bool (LicenseConfiguration entity) => LicenseConfigurationUnsafeAccessors.ExpiresAtUtc(entity).EqualsExact(default(DateTimeOffset)),
                DateTimeOffset (LicenseConfiguration instance) => LicenseConfigurationUnsafeAccessors.ExpiresAtUtc(instance),
                bool (LicenseConfiguration instance) => LicenseConfigurationUnsafeAccessors.ExpiresAtUtc(instance).EqualsExact(default(DateTimeOffset)));
            expiresAtUtc.SetSetter(
                (LicenseConfiguration entity, DateTimeOffset value) => LicenseConfigurationUnsafeAccessors.ExpiresAtUtc(entity) = value);
            expiresAtUtc.SetMaterializationSetter(
                (LicenseConfiguration entity, DateTimeOffset value) => LicenseConfigurationUnsafeAccessors.ExpiresAtUtc(entity) = value);
            expiresAtUtc.SetAccessors(
                DateTimeOffset (InternalEntityEntry entry) => LicenseConfigurationUnsafeAccessors.ExpiresAtUtc(((LicenseConfiguration)(entry.Entity))),
                DateTimeOffset (InternalEntityEntry entry) => LicenseConfigurationUnsafeAccessors.ExpiresAtUtc(((LicenseConfiguration)(entry.Entity))),
                DateTimeOffset (InternalEntityEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(expiresAtUtc, 1),
                DateTimeOffset (InternalEntityEntry entry) => entry.GetCurrentValue<DateTimeOffset>(expiresAtUtc),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            expiresAtUtc.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            expiresAtUtc.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var maxKiosks = runtimeEntityType.AddProperty(
                "MaxKiosks",
                typeof(int),
                propertyInfo: typeof(LicenseConfiguration).GetProperty("MaxKiosks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LicenseConfiguration).GetField("<MaxKiosks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxKiosks.SetGetter(
                int (LicenseConfiguration entity) => LicenseConfigurationUnsafeAccessors.MaxKiosks(entity),
                bool (LicenseConfiguration entity) => LicenseConfigurationUnsafeAccessors.MaxKiosks(entity) == 0,
                int (LicenseConfiguration instance) => LicenseConfigurationUnsafeAccessors.MaxKiosks(instance),
                bool (LicenseConfiguration instance) => LicenseConfigurationUnsafeAccessors.MaxKiosks(instance) == 0);
            maxKiosks.SetSetter(
                (LicenseConfiguration entity, int value) => LicenseConfigurationUnsafeAccessors.MaxKiosks(entity) = value);
            maxKiosks.SetMaterializationSetter(
                (LicenseConfiguration entity, int value) => LicenseConfigurationUnsafeAccessors.MaxKiosks(entity) = value);
            maxKiosks.SetAccessors(
                int (InternalEntityEntry entry) => LicenseConfigurationUnsafeAccessors.MaxKiosks(((LicenseConfiguration)(entry.Entity))),
                int (InternalEntityEntry entry) => LicenseConfigurationUnsafeAccessors.MaxKiosks(((LicenseConfiguration)(entry.Entity))),
                int (InternalEntityEntry entry) => entry.ReadOriginalValue<int>(maxKiosks, 2),
                int (InternalEntityEntry entry) => entry.GetCurrentValue<int>(maxKiosks),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            maxKiosks.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            maxKiosks.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var tier = runtimeEntityType.AddProperty(
                "Tier",
                typeof(LicenseTier),
                propertyInfo: typeof(LicenseConfiguration).GetProperty("Tier", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LicenseConfiguration).GetField("<Tier>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(string));
            tier.SetGetter(
                LicenseTier (LicenseConfiguration entity) => LicenseConfigurationUnsafeAccessors.Tier(entity),
                bool (LicenseConfiguration entity) => object.Equals(((object)(LicenseConfigurationUnsafeAccessors.Tier(entity))), ((object)(LicenseTier.Lite))),
                LicenseTier (LicenseConfiguration instance) => LicenseConfigurationUnsafeAccessors.Tier(instance),
                bool (LicenseConfiguration instance) => object.Equals(((object)(LicenseConfigurationUnsafeAccessors.Tier(instance))), ((object)(LicenseTier.Lite))));
            tier.SetSetter(
                (LicenseConfiguration entity, LicenseTier value) => LicenseConfigurationUnsafeAccessors.Tier(entity) = value);
            tier.SetMaterializationSetter(
                (LicenseConfiguration entity, LicenseTier value) => LicenseConfigurationUnsafeAccessors.Tier(entity) = value);
            tier.SetAccessors(
                LicenseTier (InternalEntityEntry entry) => LicenseConfigurationUnsafeAccessors.Tier(((LicenseConfiguration)(entry.Entity))),
                LicenseTier (InternalEntityEntry entry) => LicenseConfigurationUnsafeAccessors.Tier(((LicenseConfiguration)(entry.Entity))),
                LicenseTier (InternalEntityEntry entry) => entry.ReadOriginalValue<LicenseTier>(tier, 3),
                LicenseTier (InternalEntityEntry entry) => entry.GetCurrentValue<LicenseTier>(tier),
                object (ValueBuffer valueBuffer) => valueBuffer[3]);
            tier.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            tier.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<LicenseTier>(
                    bool (LicenseTier v1, LicenseTier v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (LicenseTier v) => ((object)v).GetHashCode(),
                    LicenseTier (LicenseTier v) => v),
                keyComparer: new ValueComparer<LicenseTier>(
                    bool (LicenseTier v1, LicenseTier v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (LicenseTier v) => ((object)v).GetHashCode(),
                    LicenseTier (LicenseTier v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<LicenseTier, string>(
                    string (LicenseTier v) => ((object)v).ToString(),
                    LicenseTier (string v) => StringEnumConverter<LicenseTier, string, LicenseTier>.ConvertToEnum(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<LicenseTier, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<LicenseTier, string>(
                        string (LicenseTier v) => ((object)v).ToString(),
                        LicenseTier (string v) => StringEnumConverter<LicenseTier, string, LicenseTier>.ConvertToEnum(v))));
            tier.SetSentinelFromProviderValue("Lite");

            var key = runtimeEntityType.AddKey(
                new[] { hardwareId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var hardwareId = runtimeEntityType.FindProperty("HardwareId");
            var expiresAtUtc = runtimeEntityType.FindProperty("ExpiresAtUtc");
            var maxKiosks = runtimeEntityType.FindProperty("MaxKiosks");
            var tier = runtimeEntityType.FindProperty("Tier");
            var key = runtimeEntityType.FindKey(new[] { hardwareId });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((LicenseConfiguration)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, DateTimeOffset, int, LicenseTier>((source.GetCurrentValue<string>(hardwareId) == null ? null : ((ValueComparer<string>)(((IProperty)hardwareId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(hardwareId))), ((ValueComparer<DateTimeOffset>)(((IProperty)expiresAtUtc).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(expiresAtUtc)), ((ValueComparer<int>)(((IProperty)maxKiosks).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(maxKiosks)), ((ValueComparer<LicenseTier>)(((IProperty)tier).GetValueComparer())).Snapshot(source.GetCurrentValue<LicenseTier>(tier)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((LicenseConfiguration)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(hardwareId) == null ? null : ((ValueComparer<string>)(((IProperty)hardwareId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(hardwareId))))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0);
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "LicenseConfigurations");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
