// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using SelfCheckoutKiosk.Domain.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class LineItemEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SelfCheckoutKiosk.Domain.Entities.LineItem",
                typeof(LineItem),
                baseEntityType,
                propertyCount: 6,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetAccessors(
                int (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && entry.ReadShadowValue<int>(0) == 0 ? entry.ReadTemporaryValue<int>(0) : entry.ReadShadowValue<int>(0))),
                int (InternalEntityEntry entry) => entry.ReadShadowValue<int>(0),
                int (InternalEntityEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<int>(id, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: 0,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(LineItem).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LineItem).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            description.SetGetter(
                string (LineItem entity) => LineItemUnsafeAccessors.Description(entity),
                bool (LineItem entity) => LineItemUnsafeAccessors.Description(entity) == null,
                string (LineItem instance) => LineItemUnsafeAccessors.Description(instance),
                bool (LineItem instance) => LineItemUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                (LineItem entity, string value) => LineItemUnsafeAccessors.Description(entity) = value);
            description.SetMaterializationSetter(
                (LineItem entity, string value) => LineItemUnsafeAccessors.Description(entity) = value);
            description.SetAccessors(
                string (InternalEntityEntry entry) => LineItemUnsafeAccessors.Description(((LineItem)(entry.Entity))),
                string (InternalEntityEntry entry) => LineItemUnsafeAccessors.Description(((LineItem)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(description, 1),
                string (InternalEntityEntry entry) => entry.GetCurrentValue<string>(description),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            description.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = SqliteStringTypeMapping.Default;

            var ean13 = runtimeEntityType.AddProperty(
                "Ean13",
                typeof(string),
                propertyInfo: typeof(LineItem).GetProperty("Ean13", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LineItem).GetField("<Ean13>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            ean13.SetGetter(
                string (LineItem entity) => LineItemUnsafeAccessors.Ean13(entity),
                bool (LineItem entity) => LineItemUnsafeAccessors.Ean13(entity) == null,
                string (LineItem instance) => LineItemUnsafeAccessors.Ean13(instance),
                bool (LineItem instance) => LineItemUnsafeAccessors.Ean13(instance) == null);
            ean13.SetSetter(
                (LineItem entity, string value) => LineItemUnsafeAccessors.Ean13(entity) = value);
            ean13.SetMaterializationSetter(
                (LineItem entity, string value) => LineItemUnsafeAccessors.Ean13(entity) = value);
            ean13.SetAccessors(
                string (InternalEntityEntry entry) => LineItemUnsafeAccessors.Ean13(((LineItem)(entry.Entity))),
                string (InternalEntityEntry entry) => LineItemUnsafeAccessors.Ean13(((LineItem)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(ean13, 2),
                string (InternalEntityEntry entry) => entry.GetCurrentValue<string>(ean13),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            ean13.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            ean13.TypeMapping = SqliteStringTypeMapping.Default;

            var quantity = runtimeEntityType.AddProperty(
                "Quantity",
                typeof(int),
                propertyInfo: typeof(LineItem).GetProperty("Quantity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LineItem).GetField("<Quantity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            quantity.SetGetter(
                int (LineItem entity) => LineItemUnsafeAccessors.Quantity(entity),
                bool (LineItem entity) => LineItemUnsafeAccessors.Quantity(entity) == 0,
                int (LineItem instance) => LineItemUnsafeAccessors.Quantity(instance),
                bool (LineItem instance) => LineItemUnsafeAccessors.Quantity(instance) == 0);
            quantity.SetSetter(
                (LineItem entity, int value) => LineItemUnsafeAccessors.Quantity(entity) = value);
            quantity.SetMaterializationSetter(
                (LineItem entity, int value) => LineItemUnsafeAccessors.Quantity(entity) = value);
            quantity.SetAccessors(
                int (InternalEntityEntry entry) => LineItemUnsafeAccessors.Quantity(((LineItem)(entry.Entity))),
                int (InternalEntityEntry entry) => LineItemUnsafeAccessors.Quantity(((LineItem)(entry.Entity))),
                int (InternalEntityEntry entry) => entry.ReadOriginalValue<int>(quantity, 3),
                int (InternalEntityEntry entry) => entry.GetCurrentValue<int>(quantity),
                object (ValueBuffer valueBuffer) => valueBuffer[3]);
            quantity.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            quantity.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var transactionGuid = runtimeEntityType.AddProperty(
                "TransactionGuid",
                typeof(Guid),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            transactionGuid.SetAccessors(
                Guid (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(4) ? entry.ReadStoreGeneratedValue<Guid>(1) : (entry.FlaggedAsTemporary(4) && entry.ReadShadowValue<Guid>(1) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(1) : entry.ReadShadowValue<Guid>(1))),
                Guid (InternalEntityEntry entry) => entry.ReadShadowValue<Guid>(1),
                Guid (InternalEntityEntry entry) => entry.ReadOriginalValue<Guid>(transactionGuid, 4),
                Guid (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<Guid>(transactionGuid, 1),
                object (ValueBuffer valueBuffer) => valueBuffer[4]);
            transactionGuid.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: 1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            transactionGuid.TypeMapping = SqliteGuidTypeMapping.Default;
            transactionGuid.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(transactionGuid));

            var unitPriceUsd = runtimeEntityType.AddProperty(
                "UnitPriceUsd",
                typeof(decimal),
                propertyInfo: typeof(LineItem).GetProperty("UnitPriceUsd", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(LineItem).GetField("<UnitPriceUsd>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            unitPriceUsd.SetGetter(
                decimal (LineItem entity) => LineItemUnsafeAccessors.UnitPriceUsd(entity),
                bool (LineItem entity) => LineItemUnsafeAccessors.UnitPriceUsd(entity) == 0M,
                decimal (LineItem instance) => LineItemUnsafeAccessors.UnitPriceUsd(instance),
                bool (LineItem instance) => LineItemUnsafeAccessors.UnitPriceUsd(instance) == 0M);
            unitPriceUsd.SetSetter(
                (LineItem entity, decimal value) => LineItemUnsafeAccessors.UnitPriceUsd(entity) = value);
            unitPriceUsd.SetMaterializationSetter(
                (LineItem entity, decimal value) => LineItemUnsafeAccessors.UnitPriceUsd(entity) = value);
            unitPriceUsd.SetAccessors(
                decimal (InternalEntityEntry entry) => LineItemUnsafeAccessors.UnitPriceUsd(((LineItem)(entry.Entity))),
                decimal (InternalEntityEntry entry) => LineItemUnsafeAccessors.UnitPriceUsd(((LineItem)(entry.Entity))),
                decimal (InternalEntityEntry entry) => entry.ReadOriginalValue<decimal>(unitPriceUsd, 5),
                decimal (InternalEntityEntry entry) => entry.GetCurrentValue<decimal>(unitPriceUsd),
                object (ValueBuffer valueBuffer) => valueBuffer[5]);
            unitPriceUsd.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            unitPriceUsd.TypeMapping = SqliteDecimalTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { transactionGuid });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TransactionGuid") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("TransactionGuid") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true,
                ownership: true);

            var lineItems = principalEntityType.AddNavigation("LineItems",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<LineItem>),
                propertyInfo: typeof(Transaction).GetProperty("LineItems", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Transaction).GetField("<LineItems>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            lineItems.SetGetter(
                List<LineItem> (Transaction entity) => TransactionUnsafeAccessors.LineItems(entity),
                bool (Transaction entity) => TransactionUnsafeAccessors.LineItems(entity) == null,
                List<LineItem> (Transaction instance) => TransactionUnsafeAccessors.LineItems(instance),
                bool (Transaction instance) => TransactionUnsafeAccessors.LineItems(instance) == null);
            lineItems.SetSetter(
                (Transaction entity, List<LineItem> value) => TransactionUnsafeAccessors.LineItems(entity) = value);
            lineItems.SetMaterializationSetter(
                (Transaction entity, List<LineItem> value) => TransactionUnsafeAccessors.LineItems(entity) = value);
            lineItems.SetAccessors(
                List<LineItem> (InternalEntityEntry entry) => TransactionUnsafeAccessors.LineItems(((Transaction)(entry.Entity))),
                List<LineItem> (InternalEntityEntry entry) => TransactionUnsafeAccessors.LineItems(((Transaction)(entry.Entity))),
                null,
                List<LineItem> (InternalEntityEntry entry) => entry.GetCurrentValue<List<LineItem>>(lineItems),
                null);
            lineItems.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            lineItems.SetCollectionAccessor<Transaction, List<LineItem>, LineItem>(
                List<LineItem> (Transaction entity) => TransactionUnsafeAccessors.LineItems(entity),
                (Transaction entity, List<LineItem> collection) => TransactionUnsafeAccessors.LineItems(entity) = ((List<LineItem>)(collection)),
                (Transaction entity, List<LineItem> collection) => TransactionUnsafeAccessors.LineItems(entity) = ((List<LineItem>)(collection)),
                List<LineItem> (Transaction entity, Action<Transaction, List<LineItem>> setter) => ClrCollectionAccessorFactory.CreateAndSet<Transaction, List<LineItem>, List<LineItem>>(entity, setter),
                List<LineItem> () => new List<LineItem>());
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var description = runtimeEntityType.FindProperty("Description");
            var ean13 = runtimeEntityType.FindProperty("Ean13");
            var quantity = runtimeEntityType.FindProperty("Quantity");
            var transactionGuid = runtimeEntityType.FindProperty("TransactionGuid");
            var unitPriceUsd = runtimeEntityType.FindProperty("UnitPriceUsd");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((LineItem)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, string, string, int, Guid, decimal>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), (source.GetCurrentValue<string>(ean13) == null ? null : ((ValueComparer<string>)(((IProperty)ean13).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(ean13))), ((ValueComparer<int>)(((IProperty)quantity).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(quantity)), ((ValueComparer<Guid>)(((IProperty)transactionGuid).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(transactionGuid)), ((ValueComparer<decimal>)(((IProperty)unitPriceUsd).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(unitPriceUsd)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int, Guid>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int)), ((ValueComparer<Guid>)(((IProperty)transactionGuid).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => ((ISnapshot)(new Snapshot<int, Guid>(default(int), default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => ((ISnapshot)(new Snapshot<int, Guid>((source.ContainsKey("Id") ? ((int)(source["Id"])) : 0), (source.ContainsKey("TransactionGuid") ? ((Guid)(source["TransactionGuid"])) : new Guid("00000000-0000-0000-0000-000000000000"))))));
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int, Guid>(default(int), default(Guid)))));
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((LineItem)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, Guid>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<Guid>)(((IProperty)transactionGuid).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(transactionGuid)))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 6,
                navigationCount: 0,
                complexPropertyCount: 0,
                originalValueCount: 6,
                shadowCount: 2,
                relationshipCount: 2,
                storeGeneratedCount: 2);
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "LineItem");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
