// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using SelfCheckoutKiosk.Domain.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    public static class LineItemUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(LineItem @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Ean13>k__BackingField")]
        public static extern ref string Ean13(LineItem @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Quantity>k__BackingField")]
        public static extern ref int Quantity(LineItem @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UnitPriceUsd>k__BackingField")]
        public static extern ref decimal UnitPriceUsd(LineItem @this);
    }
}
