// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using SelfCheckoutKiosk.Domain.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ProductEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SelfCheckoutKiosk.Domain.Entities.Product",
                typeof(Product),
                baseEntityType,
                propertyCount: 4,
                keyCount: 1);

            var ean13 = runtimeEntityType.AddProperty(
                "Ean13",
                typeof(string),
                propertyInfo: typeof(Product).GetProperty("Ean13", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Product).GetField("<Ean13>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            ean13.SetGetter(
                string (Product entity) => ProductUnsafeAccessors.Ean13(entity),
                bool (Product entity) => ProductUnsafeAccessors.Ean13(entity) == null,
                string (Product instance) => ProductUnsafeAccessors.Ean13(instance),
                bool (Product instance) => ProductUnsafeAccessors.Ean13(instance) == null);
            ean13.SetSetter(
                (Product entity, string value) => ProductUnsafeAccessors.Ean13(entity) = value);
            ean13.SetMaterializationSetter(
                (Product entity, string value) => ProductUnsafeAccessors.Ean13(entity) = value);
            ean13.SetAccessors(
                string (InternalEntityEntry entry) => ProductUnsafeAccessors.Ean13(((Product)(entry.Entity))),
                string (InternalEntityEntry entry) => ProductUnsafeAccessors.Ean13(((Product)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(ean13, 0),
                string (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<string>(ean13, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            ean13.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            ean13.TypeMapping = SqliteStringTypeMapping.Default;
            ean13.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(ean13));

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(Product).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Product).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            description.SetGetter(
                string (Product entity) => ProductUnsafeAccessors.Description(entity),
                bool (Product entity) => ProductUnsafeAccessors.Description(entity) == null,
                string (Product instance) => ProductUnsafeAccessors.Description(instance),
                bool (Product instance) => ProductUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                (Product entity, string value) => ProductUnsafeAccessors.Description(entity) = value);
            description.SetMaterializationSetter(
                (Product entity, string value) => ProductUnsafeAccessors.Description(entity) = value);
            description.SetAccessors(
                string (InternalEntityEntry entry) => ProductUnsafeAccessors.Description(((Product)(entry.Entity))),
                string (InternalEntityEntry entry) => ProductUnsafeAccessors.Description(((Product)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(description, 1),
                string (InternalEntityEntry entry) => entry.GetCurrentValue<string>(description),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            description.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = SqliteStringTypeMapping.Default;

            var khrPrice = runtimeEntityType.AddProperty(
                "KhrPrice",
                typeof(decimal),
                propertyInfo: typeof(Product).GetProperty("KhrPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Product).GetField("<KhrPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            khrPrice.SetGetter(
                decimal (Product entity) => ProductUnsafeAccessors.KhrPrice(entity),
                bool (Product entity) => ProductUnsafeAccessors.KhrPrice(entity) == 0M,
                decimal (Product instance) => ProductUnsafeAccessors.KhrPrice(instance),
                bool (Product instance) => ProductUnsafeAccessors.KhrPrice(instance) == 0M);
            khrPrice.SetSetter(
                (Product entity, decimal value) => ProductUnsafeAccessors.KhrPrice(entity) = value);
            khrPrice.SetMaterializationSetter(
                (Product entity, decimal value) => ProductUnsafeAccessors.KhrPrice(entity) = value);
            khrPrice.SetAccessors(
                decimal (InternalEntityEntry entry) => ProductUnsafeAccessors.KhrPrice(((Product)(entry.Entity))),
                decimal (InternalEntityEntry entry) => ProductUnsafeAccessors.KhrPrice(((Product)(entry.Entity))),
                decimal (InternalEntityEntry entry) => entry.ReadOriginalValue<decimal>(khrPrice, 2),
                decimal (InternalEntityEntry entry) => entry.GetCurrentValue<decimal>(khrPrice),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            khrPrice.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            khrPrice.TypeMapping = SqliteDecimalTypeMapping.Default;

            var usdPrice = runtimeEntityType.AddProperty(
                "UsdPrice",
                typeof(decimal),
                propertyInfo: typeof(Product).GetProperty("UsdPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Product).GetField("<UsdPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            usdPrice.SetGetter(
                decimal (Product entity) => ProductUnsafeAccessors.UsdPrice(entity),
                bool (Product entity) => ProductUnsafeAccessors.UsdPrice(entity) == 0M,
                decimal (Product instance) => ProductUnsafeAccessors.UsdPrice(instance),
                bool (Product instance) => ProductUnsafeAccessors.UsdPrice(instance) == 0M);
            usdPrice.SetSetter(
                (Product entity, decimal value) => ProductUnsafeAccessors.UsdPrice(entity) = value);
            usdPrice.SetMaterializationSetter(
                (Product entity, decimal value) => ProductUnsafeAccessors.UsdPrice(entity) = value);
            usdPrice.SetAccessors(
                decimal (InternalEntityEntry entry) => ProductUnsafeAccessors.UsdPrice(((Product)(entry.Entity))),
                decimal (InternalEntityEntry entry) => ProductUnsafeAccessors.UsdPrice(((Product)(entry.Entity))),
                decimal (InternalEntityEntry entry) => entry.ReadOriginalValue<decimal>(usdPrice, 3),
                decimal (InternalEntityEntry entry) => entry.GetCurrentValue<decimal>(usdPrice),
                object (ValueBuffer valueBuffer) => valueBuffer[3]);
            usdPrice.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            usdPrice.TypeMapping = SqliteDecimalTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { ean13 });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var ean13 = runtimeEntityType.FindProperty("Ean13");
            var description = runtimeEntityType.FindProperty("Description");
            var khrPrice = runtimeEntityType.FindProperty("KhrPrice");
            var usdPrice = runtimeEntityType.FindProperty("UsdPrice");
            var key = runtimeEntityType.FindKey(new[] { ean13 });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((Product)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, decimal, decimal>((source.GetCurrentValue<string>(ean13) == null ? null : ((ValueComparer<string>)(((IProperty)ean13).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(ean13))), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), ((ValueComparer<decimal>)(((IProperty)khrPrice).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(khrPrice)), ((ValueComparer<decimal>)(((IProperty)usdPrice).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(usdPrice)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((Product)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(ean13) == null ? null : ((ValueComparer<string>)(((IProperty)ean13).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(ean13))))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0);
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Products");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
