// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using SelfCheckoutKiosk.Domain.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    public static class ProductUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Ean13>k__BackingField")]
        public static extern ref string Ean13(Product @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(Product @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<KhrPrice>k__BackingField")]
        public static extern ref decimal KhrPrice(Product @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UsdPrice>k__BackingField")]
        public static extern ref decimal UsdPrice(Product @this);
    }
}
