// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using SelfCheckoutKiosk.Domain.Entities;
using SelfCheckoutKiosk.Domain.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    public static class TransactionUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TransactionGuid>k__BackingField")]
        public static extern ref Guid TransactionGuid(Transaction @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAtUtc>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAtUtc(Transaction @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PaymentMethod>k__BackingField")]
        public static extern ref PaymentMethod? PaymentMethod(Transaction @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SyncStatus>k__BackingField")]
        public static extern ref SyncStatus SyncStatus(Transaction @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenderedUsd>k__BackingField")]
        public static extern ref decimal TenderedUsd(Transaction @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TotalUsd>k__BackingField")]
        public static extern ref decimal TotalUsd(Transaction @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LineItems>k__BackingField")]
        public static extern ref List<LineItem> LineItems(Transaction @this);
    }
}
