// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using SelfCheckoutKiosk.Domain.Entities;
using SelfCheckoutKiosk.Domain.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TransactionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SelfCheckoutKiosk.Domain.Entities.Transaction",
                typeof(Transaction),
                baseEntityType,
                propertyCount: 6,
                navigationCount: 1,
                keyCount: 1);

            var transactionGuid = runtimeEntityType.AddProperty(
                "TransactionGuid",
                typeof(Guid),
                propertyInfo: typeof(Transaction).GetProperty("TransactionGuid", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Transaction).GetField("<TransactionGuid>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            transactionGuid.SetGetter(
                Guid (Transaction entity) => TransactionUnsafeAccessors.TransactionGuid(entity),
                bool (Transaction entity) => TransactionUnsafeAccessors.TransactionGuid(entity) == new Guid("00000000-0000-0000-0000-000000000000"),
                Guid (Transaction instance) => TransactionUnsafeAccessors.TransactionGuid(instance),
                bool (Transaction instance) => TransactionUnsafeAccessors.TransactionGuid(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            transactionGuid.SetSetter(
                (Transaction entity, Guid value) => TransactionUnsafeAccessors.TransactionGuid(entity) = value);
            transactionGuid.SetMaterializationSetter(
                (Transaction entity, Guid value) => TransactionUnsafeAccessors.TransactionGuid(entity) = value);
            transactionGuid.SetAccessors(
                Guid (InternalEntityEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && TransactionUnsafeAccessors.TransactionGuid(((Transaction)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : TransactionUnsafeAccessors.TransactionGuid(((Transaction)(entry.Entity))))),
                Guid (InternalEntityEntry entry) => TransactionUnsafeAccessors.TransactionGuid(((Transaction)(entry.Entity))),
                Guid (InternalEntityEntry entry) => entry.ReadOriginalValue<Guid>(transactionGuid, 0),
                Guid (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<Guid>(transactionGuid, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            transactionGuid.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            transactionGuid.TypeMapping = SqliteGuidTypeMapping.Default;
            transactionGuid.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(transactionGuid));

            var createdAtUtc = runtimeEntityType.AddProperty(
                "CreatedAtUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Transaction).GetProperty("CreatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Transaction).GetField("<CreatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAtUtc.SetGetter(
                DateTimeOffset (Transaction entity) => TransactionUnsafeAccessors.CreatedAtUtc(entity),
                bool (Transaction entity) => TransactionUnsafeAccessors.CreatedAtUtc(entity).EqualsExact(default(DateTimeOffset)),
                DateTimeOffset (Transaction instance) => TransactionUnsafeAccessors.CreatedAtUtc(instance),
                bool (Transaction instance) => TransactionUnsafeAccessors.CreatedAtUtc(instance).EqualsExact(default(DateTimeOffset)));
            createdAtUtc.SetSetter(
                (Transaction entity, DateTimeOffset value) => TransactionUnsafeAccessors.CreatedAtUtc(entity) = value);
            createdAtUtc.SetMaterializationSetter(
                (Transaction entity, DateTimeOffset value) => TransactionUnsafeAccessors.CreatedAtUtc(entity) = value);
            createdAtUtc.SetAccessors(
                DateTimeOffset (InternalEntityEntry entry) => TransactionUnsafeAccessors.CreatedAtUtc(((Transaction)(entry.Entity))),
                DateTimeOffset (InternalEntityEntry entry) => TransactionUnsafeAccessors.CreatedAtUtc(((Transaction)(entry.Entity))),
                DateTimeOffset (InternalEntityEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(createdAtUtc, 1),
                DateTimeOffset (InternalEntityEntry entry) => entry.GetCurrentValue<DateTimeOffset>(createdAtUtc),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            createdAtUtc.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAtUtc.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var paymentMethod = runtimeEntityType.AddProperty(
                "PaymentMethod",
                typeof(PaymentMethod?),
                propertyInfo: typeof(Transaction).GetProperty("PaymentMethod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Transaction).GetField("<PaymentMethod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            paymentMethod.SetGetter(
                PaymentMethod? (Transaction entity) => TransactionUnsafeAccessors.PaymentMethod(entity),
                bool (Transaction entity) => !(TransactionUnsafeAccessors.PaymentMethod(entity).HasValue),
                PaymentMethod? (Transaction instance) => TransactionUnsafeAccessors.PaymentMethod(instance),
                bool (Transaction instance) => !(TransactionUnsafeAccessors.PaymentMethod(instance).HasValue));
            paymentMethod.SetSetter(
                (Transaction entity, PaymentMethod? value) => TransactionUnsafeAccessors.PaymentMethod(entity) = (value == null ? value : ((PaymentMethod? )(((PaymentMethod)(value))))));
            paymentMethod.SetMaterializationSetter(
                (Transaction entity, PaymentMethod? value) => TransactionUnsafeAccessors.PaymentMethod(entity) = (value == null ? value : ((PaymentMethod? )(((PaymentMethod)(value))))));
            paymentMethod.SetAccessors(
                PaymentMethod? (InternalEntityEntry entry) => TransactionUnsafeAccessors.PaymentMethod(((Transaction)(entry.Entity))),
                PaymentMethod? (InternalEntityEntry entry) => TransactionUnsafeAccessors.PaymentMethod(((Transaction)(entry.Entity))),
                PaymentMethod? (InternalEntityEntry entry) => entry.ReadOriginalValue<PaymentMethod?>(paymentMethod, 2),
                PaymentMethod? (InternalEntityEntry entry) => entry.GetCurrentValue<PaymentMethod?>(paymentMethod),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            paymentMethod.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            paymentMethod.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<PaymentMethod>(
                    bool (PaymentMethod v1, PaymentMethod v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (PaymentMethod v) => ((object)v).GetHashCode(),
                    PaymentMethod (PaymentMethod v) => v),
                keyComparer: new ValueComparer<PaymentMethod>(
                    bool (PaymentMethod v1, PaymentMethod v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (PaymentMethod v) => ((object)v).GetHashCode(),
                    PaymentMethod (PaymentMethod v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<PaymentMethod, int>(
                    int (PaymentMethod value) => ((int)(value)),
                    PaymentMethod (int value) => ((PaymentMethod)(value))),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<PaymentMethod, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<PaymentMethod, int>(
                        int (PaymentMethod value) => ((int)(value)),
                        PaymentMethod (int value) => ((PaymentMethod)(value)))));
            paymentMethod.SetComparer(new NullableValueComparer<PaymentMethod>(paymentMethod.TypeMapping.Comparer));
            paymentMethod.SetKeyComparer(new NullableValueComparer<PaymentMethod>(paymentMethod.TypeMapping.KeyComparer));

            var syncStatus = runtimeEntityType.AddProperty(
                "SyncStatus",
                typeof(SyncStatus),
                propertyInfo: typeof(Transaction).GetProperty("SyncStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Transaction).GetField("<SyncStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(string));
            syncStatus.SetGetter(
                SyncStatus (Transaction entity) => TransactionUnsafeAccessors.SyncStatus(entity),
                bool (Transaction entity) => object.Equals(((object)(TransactionUnsafeAccessors.SyncStatus(entity))), ((object)(SyncStatus.Pending))),
                SyncStatus (Transaction instance) => TransactionUnsafeAccessors.SyncStatus(instance),
                bool (Transaction instance) => object.Equals(((object)(TransactionUnsafeAccessors.SyncStatus(instance))), ((object)(SyncStatus.Pending))));
            syncStatus.SetSetter(
                (Transaction entity, SyncStatus value) => TransactionUnsafeAccessors.SyncStatus(entity) = value);
            syncStatus.SetMaterializationSetter(
                (Transaction entity, SyncStatus value) => TransactionUnsafeAccessors.SyncStatus(entity) = value);
            syncStatus.SetAccessors(
                SyncStatus (InternalEntityEntry entry) => TransactionUnsafeAccessors.SyncStatus(((Transaction)(entry.Entity))),
                SyncStatus (InternalEntityEntry entry) => TransactionUnsafeAccessors.SyncStatus(((Transaction)(entry.Entity))),
                SyncStatus (InternalEntityEntry entry) => entry.ReadOriginalValue<SyncStatus>(syncStatus, 3),
                SyncStatus (InternalEntityEntry entry) => entry.GetCurrentValue<SyncStatus>(syncStatus),
                object (ValueBuffer valueBuffer) => valueBuffer[3]);
            syncStatus.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            syncStatus.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<SyncStatus>(
                    bool (SyncStatus v1, SyncStatus v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (SyncStatus v) => ((object)v).GetHashCode(),
                    SyncStatus (SyncStatus v) => v),
                keyComparer: new ValueComparer<SyncStatus>(
                    bool (SyncStatus v1, SyncStatus v2) => object.Equals(((object)(v1)), ((object)(v2))),
                    int (SyncStatus v) => ((object)v).GetHashCode(),
                    SyncStatus (SyncStatus v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<SyncStatus, string>(
                    string (SyncStatus v) => ((object)v).ToString(),
                    SyncStatus (string v) => StringEnumConverter<SyncStatus, string, SyncStatus>.ConvertToEnum(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<SyncStatus, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<SyncStatus, string>(
                        string (SyncStatus v) => ((object)v).ToString(),
                        SyncStatus (string v) => StringEnumConverter<SyncStatus, string, SyncStatus>.ConvertToEnum(v))));
            syncStatus.SetSentinelFromProviderValue("Pending");

            var tenderedUsd = runtimeEntityType.AddProperty(
                "TenderedUsd",
                typeof(decimal),
                propertyInfo: typeof(Transaction).GetProperty("TenderedUsd", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Transaction).GetField("<TenderedUsd>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            tenderedUsd.SetGetter(
                decimal (Transaction entity) => TransactionUnsafeAccessors.TenderedUsd(entity),
                bool (Transaction entity) => TransactionUnsafeAccessors.TenderedUsd(entity) == 0M,
                decimal (Transaction instance) => TransactionUnsafeAccessors.TenderedUsd(instance),
                bool (Transaction instance) => TransactionUnsafeAccessors.TenderedUsd(instance) == 0M);
            tenderedUsd.SetSetter(
                (Transaction entity, decimal value) => TransactionUnsafeAccessors.TenderedUsd(entity) = value);
            tenderedUsd.SetMaterializationSetter(
                (Transaction entity, decimal value) => TransactionUnsafeAccessors.TenderedUsd(entity) = value);
            tenderedUsd.SetAccessors(
                decimal (InternalEntityEntry entry) => TransactionUnsafeAccessors.TenderedUsd(((Transaction)(entry.Entity))),
                decimal (InternalEntityEntry entry) => TransactionUnsafeAccessors.TenderedUsd(((Transaction)(entry.Entity))),
                decimal (InternalEntityEntry entry) => entry.ReadOriginalValue<decimal>(tenderedUsd, 4),
                decimal (InternalEntityEntry entry) => entry.GetCurrentValue<decimal>(tenderedUsd),
                object (ValueBuffer valueBuffer) => valueBuffer[4]);
            tenderedUsd.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            tenderedUsd.TypeMapping = SqliteDecimalTypeMapping.Default;

            var totalUsd = runtimeEntityType.AddProperty(
                "TotalUsd",
                typeof(decimal),
                propertyInfo: typeof(Transaction).GetProperty("TotalUsd", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Transaction).GetField("<TotalUsd>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            totalUsd.SetGetter(
                decimal (Transaction entity) => TransactionUnsafeAccessors.TotalUsd(entity),
                bool (Transaction entity) => TransactionUnsafeAccessors.TotalUsd(entity) == 0M,
                decimal (Transaction instance) => TransactionUnsafeAccessors.TotalUsd(instance),
                bool (Transaction instance) => TransactionUnsafeAccessors.TotalUsd(instance) == 0M);
            totalUsd.SetSetter(
                (Transaction entity, decimal value) => TransactionUnsafeAccessors.TotalUsd(entity) = value);
            totalUsd.SetMaterializationSetter(
                (Transaction entity, decimal value) => TransactionUnsafeAccessors.TotalUsd(entity) = value);
            totalUsd.SetAccessors(
                decimal (InternalEntityEntry entry) => TransactionUnsafeAccessors.TotalUsd(((Transaction)(entry.Entity))),
                decimal (InternalEntityEntry entry) => TransactionUnsafeAccessors.TotalUsd(((Transaction)(entry.Entity))),
                decimal (InternalEntityEntry entry) => entry.ReadOriginalValue<decimal>(totalUsd, 5),
                decimal (InternalEntityEntry entry) => entry.GetCurrentValue<decimal>(totalUsd),
                object (ValueBuffer valueBuffer) => valueBuffer[5]);
            totalUsd.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            totalUsd.TypeMapping = SqliteDecimalTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { transactionGuid });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var transactionGuid = runtimeEntityType.FindProperty("TransactionGuid");
            var createdAtUtc = runtimeEntityType.FindProperty("CreatedAtUtc");
            var paymentMethod = runtimeEntityType.FindProperty("PaymentMethod");
            var syncStatus = runtimeEntityType.FindProperty("SyncStatus");
            var tenderedUsd = runtimeEntityType.FindProperty("TenderedUsd");
            var totalUsd = runtimeEntityType.FindProperty("TotalUsd");
            var key = runtimeEntityType.FindKey(new[] { transactionGuid });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var lineItems = runtimeEntityType.FindNavigation("LineItems");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((Transaction)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, DateTimeOffset, PaymentMethod?, SyncStatus, decimal, decimal>(((ValueComparer<Guid>)(((IProperty)transactionGuid).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(transactionGuid)), ((ValueComparer<DateTimeOffset>)(((IProperty)createdAtUtc).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(createdAtUtc)), (source.GetCurrentValue<PaymentMethod?>(paymentMethod) == null ? null : ((ValueComparer<PaymentMethod?>)(((IProperty)paymentMethod).GetValueComparer())).Snapshot(source.GetCurrentValue<PaymentMethod?>(paymentMethod))), ((ValueComparer<SyncStatus>)(((IProperty)syncStatus).GetValueComparer())).Snapshot(source.GetCurrentValue<SyncStatus>(syncStatus)), ((ValueComparer<decimal>)(((IProperty)tenderedUsd).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(tenderedUsd)), ((ValueComparer<decimal>)(((IProperty)totalUsd).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(totalUsd)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)transactionGuid).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((Transaction)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, object>(((ValueComparer<Guid>)(((IProperty)transactionGuid).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(transactionGuid)), SnapshotFactoryFactory.SnapshotCollection(TransactionUnsafeAccessors.LineItems(entity)))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 6,
                navigationCount: 1,
                complexPropertyCount: 0,
                originalValueCount: 6,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 1);
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Transactions");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
