<Project Sdk="Microsoft.NET.Sdk">
  <!-- DOMAIN LAYER — centre of the onion. References NOTHING.
       No frameworks, no EF Core, no hardware, no DI. Pure C#.
       Owner: Back-End Developer. -->
  <PropertyGroup>
    <RootNamespace>SelfCheckoutKiosk.Domain</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Workloads.10.0.100" Version="10.110.0" />
  </ItemGroup>
</Project>
