<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SelfCheckoutKiosk_Core_Tests</RootNamespace>
    <OutputType>Library</OutputType>
    <Platforms>AnyCPU;ARM64;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Microsoft.NET.Workloads.10.0.100" Version="10.110.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SelfCheckoutKiosk.Core\SelfCheckoutKiosk.Core.csproj" />
  </ItemGroup>
</Project>
