// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfCheckoutKiosk.Infrastructure.Data;

#nullable disable

namespace SelfCheckoutKiosk.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KioskDbContext))]
    [Migration("20260810022453_InitialKioskPersistence")]
    partial class InitialKioskPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SelfCheckoutKiosk.Domain.Entities.LicenseConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiModuleEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CashModuleEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ErpSyncEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxKiosks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignedToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.ToTable("LicenseConfigurations", (string)null);
                });

            modelBuilder.Entity("SelfCheckoutKiosk.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean13")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UsdPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ean13")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("SelfCheckoutKiosk.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionGuid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangeKhr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangeUsd")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeRateKhrPerUsd")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TenderedUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalUsd")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionGuid");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("SyncStatus");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("SelfCheckoutKiosk.Domain.Entities.TransactionLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotalUsd")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransactionGuid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceUsdSnapshot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionGuid");

                    b.ToTable("TransactionLines", (string)null);
                });

            modelBuilder.Entity("SelfCheckoutKiosk.Domain.Entities.TransactionLine", b =>
                {
                    b.HasOne("SelfCheckoutKiosk.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
